### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joshdekock** [SMOKE5/PSID_Dumper#1]
What's the license for this?
CC0/Unlicense, MIT, BSD may be good choices

**Comment by SMOKE5** [comment]
Thanks for bringing that to my attention
https://github.com/SMOKE5/PSID_Dumper/commit/778247ef95bc4761850f9ceaa5fffa965ba770c9

**Comment by joshdekock** [comment]
With the GPL you need to specify if it uses the 'or Later' clause (a clause which is helpful for people to 'upgrade' the license to a later GPL license if an issue with the current one is found).

**Comment by SMOKE5** [comment]
I uploaded the wrong one. I meant to use MIT for this. I shouldn't be using my phone to do this lol
